### ISSUE TITLE
Add support for 3DS Max 2022

### ISSUE THREAD

**Issue by UnrealKaraulov** [NeilJed/3DSMax-SMD-Exporter-Plugin#5]
@NeilJed impossible to add support 2022 max ?

**Comment by NeilJed** [comment]
I'm not an active Max developer these days so missed Max 2022 was out. I've looked at the SDK changes and yes, I need to recompile it but the toolchain is the same as 2020/2021 so it shouldn't be a problem. I'll take a look when I can.
